version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    target-branch: 'dev'
    labels:
      - 'dependencies'
    groups:
      next:
        patterns:
          - 'next'
          - '@next/*'
          - 'react'
          - 'react-dom'
      tooling:
        patterns:
          - 'typescript'
          - 'eslint*'
          - 'prettier*'
          - 'turbo'
          - '@types/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'dev'
